// ─── Models ──────────────────────────────────────────────────────────────────
export const MODELS = [
  { id: "claude-sonnet-4-5", label: "Claude Sonnet 4.5", provider: "Anthropic", tag: "Latest" },
  { id: "claude-3-7-sonnet", label: "Claude 3.7 Sonnet", provider: "Anthropic", tag: "" },
  { id: "claude-3-5-sonnet", label: "Claude 3.5 Sonnet", provider: "Anthropic", tag: "" },
  { id: "gpt-4o", label: "GPT-4o", provider: "OpenAI", tag: "" },
  { id: "gpt-4o-mini", label: "GPT-4o mini", provider: "OpenAI", tag: "Fast" },
  { id: "o3", label: "o3", provider: "OpenAI", tag: "" },
  { id: "o3-mini", label: "o3-mini", provider: "OpenAI", tag: "" },
  { id: "o1", label: "o1", provider: "OpenAI", tag: "" },
  { id: "gemini-2-0-flash", label: "Gemini 2.0 Flash", provider: "Google", tag: "Fast" },
  { id: "gemini-1-5-pro", label: "Gemini 1.5 Pro", provider: "Google", tag: "" },
] as const;

export type ModelId = (typeof MODELS)[number]["id"];

// ─── Modes ────────────────────────────────────────────────────────────────────
export const MODES = ["Ask", "Edit", "Agent"] as const;
export type Mode = (typeof MODES)[number];

export const MODE_DESCRIPTIONS: Record<Mode, string> = {
  Ask: "Ask questions and get answers",
  Edit: "Edit files in your workspace",
  Agent: "Autonomously edit files, run commands, and iterate",
};

// ─── Slash commands (exact text from package.nls.json) ───────────────────────
export const SLASH_COMMANDS = [
  {
    name: "explain",
    desc: "Explain how the code in your active editor works",
    sampleRequest: "",
    icon: "$(book)",
    modes: ["Ask", "Edit", "Agent"],
  },
  {
    name: "fix",
    desc: "Propose a fix for the problems in the selected code",
    sampleRequest: "There is a problem in this code. Rewrite the code to show it with the bug fixed.",
    icon: "$(wrench)",
    modes: ["Ask", "Edit", "Agent"],
  },
  {
    name: "tests",
    desc: "Generate unit tests for the selected code",
    sampleRequest: "",
    icon: "$(beaker)",
    modes: ["Ask", "Edit", "Agent"],
  },
  {
    name: "doc",
    desc: "Add documentation comment for this symbol",
    sampleRequest: "",
    icon: "$(comment)",
    modes: ["Ask", "Edit", "Agent"],
  },
  {
    name: "review",
    desc: "Review the selected code in your active editor",
    sampleRequest: "",
    icon: "$(search)",
    modes: ["Ask", "Edit", "Agent"],
  },
  {
    name: "new",
    desc: "Scaffold code for a new file or project in a workspace",
    sampleRequest: "Create a RESTful API server using typescript",
    icon: "$(new-folder)",
    modes: ["Ask", "Edit", "Agent"],
  },
  {
    name: "newNotebook",
    desc: "Create a new Jupyter Notebook",
    sampleRequest: "How do I create a notebook to load data from a csv file?",
    icon: "$(notebook)",
    modes: ["Ask", "Edit", "Agent"],
  },
  {
    name: "semanticSearch",
    desc: "Find relevant code to your query",
    sampleRequest: "Where is the toolbar code?",
    icon: "$(search-fuzzy)",
    modes: ["Ask", "Edit", "Agent"],
  },
  {
    name: "setupTests",
    desc: "Set up tests in your project (Experimental)",
    sampleRequest: "add playwright tests to my project",
    icon: "$(testing-run-icon)",
    modes: ["Ask", "Edit", "Agent"],
  },
  {
    name: "compact",
    desc: "Free up context by compacting the conversation history. Optionally include extra instructions for compaction.",
    sampleRequest: "",
    icon: "$(fold)",
    modes: ["Agent"],
  },
  {
    name: "clear",
    desc: "Clear the conversation",
    sampleRequest: "",
    icon: "$(trash)",
    modes: ["Ask", "Edit", "Agent"],
  },
  {
    name: "remember",
    desc: "Save a fact to persistent memory (e.g. /remember I prefer TypeScript)",
    sampleRequest: "",
    icon: "$(bookmark)",
    modes: ["Ask", "Edit", "Agent"],
  },
  {
    name: "jcl",
    desc: "Generate complete, ready-to-submit JCL for a z/OS task (compile, link-edit, sort, copy, IDCAMS…)",
    sampleRequest: "Generate JCL to compile and link a COBOL program named MYPRG from MY.COBOL.LIB",
    icon: "$(gear)",
    modes: ["Ask", "Edit", "Agent"],
  },
  {
    name: "cobol",
    desc: "Write, fix, or explain COBOL programs for z/OS batch or CICS",
    sampleRequest: "Write a COBOL program that reads a VSAM KSDS file and prints a report",
    icon: "$(code)",
    modes: ["Ask", "Edit", "Agent"],
  },
   {
     name: "datasets",
     desc: "IBM dataset help — naming rules, allocation, VSAM, GDGs, PDS/PDSE management",
     sampleRequest: "How do I allocate a VSAM KSDS cluster with 100 MB primary space?",
     icon: "$(database)",
     modes: ["Ask", "Edit", "Agent"],
   },
   {
     name: "analyze",
     desc: "Analyze COBOL code structure, complexity metrics, and refactoring suggestions",
     sampleRequest: "Analyze this COBOL program for dead code and complexity",
     icon: "$(inspect)",
     modes: ["Ask", "Edit", "Agent"],
   },
   {
     name: "deploy",
     desc: "Orchestrate CI/CD pipelines, build steps, and deployment automation",
     sampleRequest: "Deploy this application to production with rollback support",
     icon: "$(rocket)",
     modes: ["Agent"],
   },
   {
     name: "debug",
     desc: "Start a debug session with breakpoints and variable inspection",
     sampleRequest: "Debug this COBOL program and inspect variables",
     icon: "$(debug-start)",
     modes: ["Agent"],
   },
   {
     name: "test",
     desc: "Create and run test suites with code coverage and performance metrics",
     sampleRequest: "Generate unit tests and check code coverage",
     icon: "$(testing-run-icon)",
     modes: ["Ask", "Edit", "Agent"],
   },
    {
      name: "fix-error",
      desc: "Analyze errors and abend codes, identify root causes, and suggest fixes",
      sampleRequest: "Analyze this S0C7 error and suggest a fix",
      icon: "$(error)",
      modes: ["Ask", "Edit", "Agent"],
    },
    {
      name: "query",
      desc: "Execute database queries, apply masking, track lineage, and validate data quality",
      sampleRequest: "Execute an optimized query for customer data",
      icon: "$(database)",
      modes: ["Ask", "Edit", "Agent"],
    },
    {
      name: "secure",
      desc: "Run security scans, check compliance, detect threats, and manage certificates",
      sampleRequest: "Scan for vulnerabilities and check SOC2 compliance",
      icon: "$(shield)",
      modes: ["Ask", "Edit", "Agent"],
    },
    {
      name: "integrate",
      desc: "Configure APIs, message queues, cloud providers, and webhooks",
      sampleRequest: "Set up REST API integration with AWS",
      icon: "$(plug)",
      modes: ["Ask", "Edit", "Agent"],
    },
     {
       name: "analytics",
       desc: "Create dashboards, run ML analysis, generate reports, and configure alerts",
       sampleRequest: "Create a real-time performance dashboard with ML anomaly detection",
       icon: "$(graph)",
       modes: ["Ask", "Edit", "Agent"],
     },
     {
       name: "dashboard",
       desc: "Create and manage interactive UI dashboards with widgets and visualizations",
       sampleRequest: "Create a performance monitoring dashboard with charts and metrics",
       icon: "$(layout)",
       modes: ["Ask", "Edit", "Agent"],
     },
     {
       name: "docs",
       desc: "Generate comprehensive documentation including API specs, architecture diagrams, and runbooks",
       sampleRequest: "Generate API documentation and deployment runbook",
       icon: "$(book)",
       modes: ["Ask", "Edit", "Agent"],
     },
     {
       name: "ml",
       desc: "Train machine learning models, generate predictions, and analyze data patterns",
       sampleRequest: "Train a classification model and predict outcomes",
       icon: "$(beaker)",
       modes: ["Ask", "Edit", "Agent"],
     },
      {
        name: "workflow",
        desc: "Create and optimize intelligent workflows with autonomous task execution",
        sampleRequest: "Build an automated data processing workflow",
        icon: "$(play)",
        modes: ["Ask", "Edit", "Agent"],
      },
      // ═══════════════════════════════════════════════════════════════════
      // PHASE 2 ADVANCED DEVELOPMENT TOOLS (Modules 13-19)
      // ═══════════════════════════════════════════════════════════════════
      {
        name: "debug-visual",
        desc: "Create visual debugging sessions with call graphs, variable tracking, and execution flow diagrams",
        sampleRequest: "Start a visual debug session for this COBOL program with call graph visualization",
        icon: "$(debug-view-expression)",
        modes: ["Agent"],
      },
      {
        name: "test-automation",
        desc: "Generate comprehensive test suites with automated test case generation and coverage analysis",
        sampleRequest: "Generate automated unit tests and measure code coverage",
        icon: "$(testing-run-icon)",
        modes: ["Ask", "Edit", "Agent"],
      },
      {
        name: "regression-tests",
        desc: "Build and execute regression test suites with baseline comparison and deviation detection",
        sampleRequest: "Create a regression test suite comparing new version to baseline",
        icon: "$(test-view-icon)",
        modes: ["Agent"],
      },
      {
        name: "screen-automate",
        desc: "Automate TN3270 screen interactions with field automation and screen capture analysis",
        sampleRequest: "Create an automation script for TN3270 screen navigation and data entry",
        icon: "$(terminal)",
        modes: ["Agent"],
      },
      {
        name: "extract-fields",
        desc: "Extract, parse, and validate data fields from COBOL programs and screen outputs",
        sampleRequest: "Extract and validate all data fields from this COBOL copybook",
        icon: "$(database)",
        modes: ["Ask", "Edit", "Agent"],
      },
      {
        name: "cicd-pipeline",
        desc: "Create and orchestrate CI/CD pipelines with multi-stage builds and deployment automation",
        sampleRequest: "Create a CI/CD pipeline with build, test, and deployment stages",
        icon: "$(repo)",
        modes: ["Agent"],
      },
      {
        name: "deploy-release",
        desc: "Manage application releases with deployment plans, approval workflows, and rollback automation",
        sampleRequest: "Create a release package and deploy to production with rollback support",
        icon: "$(rocket)",
        modes: ["Agent"],
      },

      // ═══════════════════════════════════════════════════════════════════
      // PHASE 2 ADVANCED OPTIMIZATION (Modules 20-26)
      // ═══════════════════════════════════════════════════════════════════
      {
        name: "perf-optimize",
        desc: "Analyze and optimize application performance with bottleneck detection and recommendations",
        sampleRequest: "Analyze performance metrics and provide optimization recommendations",
        icon: "$(dashboard)",
        modes: ["Ask", "Agent"],
      },
      {
        name: "memory-analyze",
        desc: "Analyze memory usage patterns, detect leaks, and optimize memory allocation",
        sampleRequest: "Analyze memory allocation patterns and detect potential leaks",
        icon: "$(vm)",
        modes: ["Ask", "Agent"],
      },
      {
        name: "batch-jobs",
        desc: "Manage and monitor batch job lifecycle with scheduling and resource optimization",
        sampleRequest: "Create a scheduled batch job with dependency management",
        icon: "$(package)",
        modes: ["Ask", "Agent"],
      },
      {
        name: "data-validate",
        desc: "Validate data against schemas with quality metrics and compliance checking",
        sampleRequest: "Create validation rules and perform batch data validation",
        icon: "$(checklist)",
        modes: ["Ask", "Edit", "Agent"],
      },
      {
        name: "metrics-dashboard",
        desc: "Collect code metrics, track code quality, and generate comprehensive dashboards",
        sampleRequest: "Generate code metrics dashboard and identify quality issues",
        icon: "$(graph)",
        modes: ["Ask", "Agent"],
      },
      {
        name: "compliance-check",
        desc: "Perform compliance checks against regulatory frameworks with audit trails",
        sampleRequest: "Run compliance checks against HIPAA and SOX frameworks",
        icon: "$(shield)",
        modes: ["Ask", "Agent"],
      },
      {
        name: "workflow-optimize",
        desc: "Define and optimize workflows with task orchestration and performance analysis",
        sampleRequest: "Create a workflow and analyze for optimization opportunities",
        icon: "$(organization)",
        modes: ["Ask", "Agent"],
      },
      {
        name: "security-audit",
        desc: "Perform security audits and vulnerability assessments with compliance checks",
        sampleRequest: "Run security audit and identify vulnerabilities",
        icon: "$(shield)",
        modes: ["Ask", "Agent"],
      },
      {
        name: "api-gateway",
        desc: "Register and manage API endpoints with rate limiting and authentication",
        sampleRequest: "Register a new API endpoint with rate limiting",
        icon: "$(plug)",
        modes: ["Ask", "Agent"],
      },
      {
        name: "cache-manager",
        desc: "Manage distributed caches with TTL and invalidation strategies",
        sampleRequest: "Setup cache policy and configure invalidation rules",
        icon: "$(database)",
        modes: ["Ask", "Agent"],
      },
      {
        name: "logging-analytics",
        desc: "Configure structured logging with real-time analytics and alerting",
        sampleRequest: "Setup logging aggregation and create alert rules",
        icon: "$(output)",
        modes: ["Ask", "Agent"],
      },
      {
        name: "change-tracker",
        desc: "Track code changes with approval workflows and impact analysis",
        sampleRequest: "Create change record and analyze impact",
        icon: "$(git-compare)",
        modes: ["Ask", "Agent"],
      },
      {
        name: "dependency-resolver",
        desc: "Resolve dependencies and detect conflicts with version compatibility checks",
        sampleRequest: "Analyze dependencies and detect circular references",
        icon: "$(link)",
        modes: ["Ask", "Agent"],
      },
      {
        name: "health-monitor",
        desc: "Monitor system health with real-time checks and resource tracking",
        sampleRequest: "Check system health and resource utilization",
        icon: "$(pulse)",
        modes: ["Ask", "Agent"],
      },
      {
        name: "release-manager",
        desc: "Plan releases with build management and deployment coordination",
        sampleRequest: "Create release plan and manage deployment",
        icon: "$(rocket)",
        modes: ["Ask", "Agent"],
      },
      {
         name: "integration-tester",
         desc: "Create and execute integration tests with comprehensive reporting",
         sampleRequest: "Create test suite and run integration tests",
         icon: "$(testing)",
         modes: ["Ask", "Agent"],
       },
       // ═══════════════════════════════════════════════════════════════════
       // PHASE 3 BATCH 1: INFRASTRUCTURE & OPERATIONS (Modules 36-44)
       // ═══════════════════════════════════════════════════════════════════
       {
         name: "infrastructure-provisioner",
         desc: "Provision and manage infrastructure with IaC templates and lifecycle management",
         sampleRequest: "Create infrastructure provisioning plan and execute deployment",
         icon: "$(server)",
         modes: ["Ask", "Agent"],
       },
       {
         name: "disaster-recovery",
         desc: "Manage disaster recovery plans with backup verification and failover testing",
         sampleRequest: "Create DR plan and schedule failover drills",
         icon: "$(shield-check)",
         modes: ["Ask", "Agent"],
       },
       {
         name: "capacity-planner",
         desc: "Forecast capacity requirements with utilization trends and recommendations",
         sampleRequest: "Analyze capacity trends and generate capacity report",
         icon: "$(graph)",
         modes: ["Ask", "Agent"],
       },
       {
         name: "load-balancer",
         desc: "Configure load balancing with distribution metrics and performance monitoring",
         sampleRequest: "Setup load balancer with backend servers",
         icon: "$(network)",
         modes: ["Ask", "Agent"],
       },
       {
         name: "backup-manager",
         desc: "Manage enterprise backups with scheduling, verification, and restoration",
         sampleRequest: "Create backup job and configure restore points",
         icon: "$(save)",
         modes: ["Ask", "Agent"],
       },
       {
         name: "configuration-manager",
         desc: "Manage configurations with version control, templates, and rollback capabilities",
         sampleRequest: "Create configuration template and manage versions",
         icon: "$(settings)",
         modes: ["Ask", "Agent"],
       },
       {
         name: "cost-analyzer",
         desc: "Analyze and optimize costs with resource breakdown and forecasting",
         sampleRequest: "Generate cost analysis and optimization recommendations",
         icon: "$(money)",
         modes: ["Ask", "Agent"],
       },
       {
         name: "network-monitor",
         desc: "Monitor network performance with traffic metrics and latency analysis",
         sampleRequest: "Monitor network health and generate traffic report",
         icon: "$(broadcast)",
         modes: ["Ask", "Agent"],
       },
       {
         name: "compliance-auditor",
         desc: "Execute compliance audits with evidence collection and remediation tracking",
         sampleRequest: "Run compliance audit and track remediation actions",
         icon: "$(verified-filled)",
         modes: ["Ask", "Agent"],
       },
       // ═══════════════════════════════════════════════════════════════════
       // PHASE 3 BATCH 2: ADVANCED ANALYTICS & INTELLIGENCE (Modules 45-53)
       // ═══════════════════════════════════════════════════════════════════
       {
         name: "data-analytics",
         desc: "Analyze datasets with custom queries and comprehensive result reporting",
         sampleRequest: "Query dataset and analyze trends",
         icon: "$(microscope)",
         modes: ["Ask", "Agent"],
       },
       {
         name: "anomaly-detector",
         desc: "Detect anomalies with baseline comparison and threshold configuration",
         sampleRequest: "Configure anomaly detection rules and run analysis",
         icon: "$(warning)",
         modes: ["Ask", "Agent"],
       },
       {
         name: "trend-analyzer",
         desc: "Analyze time series data with pattern detection and forecasting",
         sampleRequest: "Analyze trends and generate forecasts",
         icon: "$(trending-up)",
         modes: ["Ask", "Agent"],
       },
       {
         name: "predictive-engine",
         desc: "Build and train prediction models with accuracy metrics and forecasts",
         sampleRequest: "Train prediction model and generate forecasts",
         icon: "$(lightbulb)",
         modes: ["Ask", "Agent"],
       },
       {
         name: "intelligence-system",
         desc: "Generate actionable intelligence from multiple data sources",
         sampleRequest: "Analyze data sources and generate intelligence insights",
         icon: "$(insights)",
         modes: ["Ask", "Agent"],
       },
       {
         name: "decision-optimizer",
         desc: "Optimize decisions using criteria evaluation and scoring matrix",
         sampleRequest: "Evaluate decision options and generate optimization results",
         icon: "$(git-compare)",
         modes: ["Ask", "Agent"],
       },
       {
         name: "pattern-recognizer",
         desc: "Recognize data patterns with library matching and classification",
         sampleRequest: "Analyze patterns and classify sequences",
         icon: "$(symbol-pattern)",
         modes: ["Ask", "Agent"],
       },
       {
         name: "forecasting-engine",
         desc: "Create forecasts with scenario modeling and confidence intervals",
         sampleRequest: "Generate forecast with scenario analysis",
         icon: "$(crystal-ball)",
         modes: ["Ask", "Agent"],
       },
       {
         name: "business-intelligence",
         desc: "Generate business insights with KPIs, dashboards, and executive reports",
         sampleRequest: "Create business intelligence dashboard with KPIs",
         icon: "$(chart-bar)",
         modes: ["Ask", "Agent"],
       },
       // ═══════════════════════════════════════════════════════════════════
       // PHASE 3 BATCH 3: ADVANCED SECURITY & GOVERNANCE (Modules 54-62)
       // ═══════════════════════════════════════════════════════════════════
       {
         name: "threat-intelligence",
         desc: "Track threats with indicators, actors, and campaign analysis",
         sampleRequest: "Analyze threat indicators and generate threat report",
         icon: "$(warning)",
         modes: ["Ask", "Agent"],
       },
       {
         name: "vulnerability-management",
         desc: "Manage vulnerabilities with assessments, patches, and remediation planning",
         sampleRequest: "Execute vulnerability assessment and create remediation plan",
         icon: "$(bug)",
         modes: ["Ask", "Agent"],
       },
       {
         name: "encryption-manager",
         desc: "Manage encryption keys and policies with rotation and metrics",
         sampleRequest: "Configure encryption policies and manage key rotation",
         icon: "$(lock)",
         modes: ["Ask", "Agent"],
       },
       {
         name: "identity-manager",
         desc: "Manage identities and access rights with authentication and policies",
         sampleRequest: "Manage identity profiles and access rights",
         icon: "$(person)",
         modes: ["Ask", "Agent"],
       },
       {
         name: "audit-logger",
         desc: "Log and query audit events with comprehensive reporting",
         sampleRequest: "Query audit logs and generate audit report",
         icon: "$(notebook)",
         modes: ["Ask", "Agent"],
       },
       {
         name: "policy-engine",
         desc: "Define and enforce policies with violation tracking and reporting",
         sampleRequest: "Create policy rules and monitor enforcement",
         icon: "$(law)",
         modes: ["Ask", "Agent"],
       },
       {
         name: "incident-responder",
         desc: "Respond to security incidents with playbooks and remediation steps",
         sampleRequest: "Execute incident response plan and track remediation",
         icon: "$(emergency)",
         modes: ["Ask", "Agent"],
       },
       {
         name: "governance-manager",
         desc: "Manage governance with policies, risks, and compliance frameworks",
         sampleRequest: "Create governance policies and perform risk assessment",
         icon: "$(organization)",
         modes: ["Ask", "Agent"],
        },
        {
          name: "secrets-vault",
          desc: "Secure secrets with versioning, access logs, and policy enforcement",
          sampleRequest: "Store secrets and manage access policies",
          icon: "$(key)",
          modes: ["Ask", "Agent"],
        },
        // ═══════════════════════════════════════════════════════════════════
        // PHASE 4: NEXT-GENERATION AI & MODERNIZATION (Modules 63-71)
        // ═══════════════════════════════════════════════════════════════════
        {
          name: "code-modernization",
          desc: "Transform legacy COBOL to modern architectures with ROI analysis",
          sampleRequest: "Analyze COBOL program and recommend modernization path",
          icon: "$(refresh)",
          modes: ["Ask", "Agent"],
        },
        {
          name: "ai-code-generator",
          desc: "Generate code from descriptions with LLM-powered intelligence",
          sampleRequest: "Generate TypeScript function from description",
          icon: "$(sparkle)",
          modes: ["Ask", "Agent"],
        },
        {
          name: "stream-analytics",
          desc: "Process real-time streaming data with anomaly detection",
          sampleRequest: "Analyze event stream and detect anomalies",
          icon: "$(zap)",
          modes: ["Ask", "Agent"],
        },
        {
          name: "compliance-workflow",
          desc: "Automate compliance workflows with policy enforcement",
          sampleRequest: "Execute compliance testing and generate report",
          icon: "$(check)",
          modes: ["Ask", "Agent"],
        },
        {
          name: "aiops-intelligence",
          desc: "Correlate incidents with ML-based root cause analysis",
          sampleRequest: "Analyze incidents and identify root causes",
          icon: "$(lightbulb)",
          modes: ["Ask", "Agent"],
        },
        {
          name: "knowledge-discovery",
          desc: "Semantic search and intelligent knowledge graph navigation",
          sampleRequest: "Search knowledge base and find related content",
          icon: "$(search)",
          modes: ["Ask", "Agent"],
        },
        {
          name: "cost-optimization",
          desc: "Real-time cost monitoring and optimization recommendations",
          sampleRequest: "Analyze cloud costs and generate optimization plan",
          icon: "$(money)",
          modes: ["Ask", "Agent"],
        },
        {
          name: "gitops-management",
          desc: "Declarative infrastructure with drift detection and policy enforcement",
          sampleRequest: "Deploy infrastructure and detect configuration drift",
          icon: "$(git-branch)",
          modes: ["Ask", "Agent"],
        },
         {
           name: "team-collaboration",
           desc: "Coordinate team development with code reviews and learning paths",
           sampleRequest: "Create code review and schedule pair programming session",
           icon: "$(people)",
           modes: ["Ask", "Agent"],
         },
         // ═══════════════════════════════════════════════════════════════════
         // PHASE 5: ENTERPRISE DATA & INTEGRATION PLATFORMS (Modules 72-86)
         // ═══════════════════════════════════════════════════════════════════
         {
           name: "data-lake",
           desc: "Manage data lakes with cataloging, metadata, and quality governance",
           sampleRequest: "Create data lake catalog and configure governance rules",
           icon: "$(database)",
           modes: ["Ask", "Agent"],
         },
         {
           name: "event-driven",
           desc: "Design event-driven architecture with pub/sub and event streaming",
           sampleRequest: "Design event streaming pipeline with pub/sub messaging",
           icon: "$(zap)",
           modes: ["Ask", "Agent"],
         },
         {
           name: "api-management",
           desc: "Manage API lifecycle with versioning, documentation, and governance",
           sampleRequest: "Create API version and manage deployment pipeline",
           icon: "$(plug)",
           modes: ["Ask", "Agent"],
         },
         {
           name: "customer-experience",
           desc: "Orchestrate omnichannel customer journeys with personalization",
           sampleRequest: "Design omnichannel customer experience journey",
           icon: "$(person-filled)",
           modes: ["Ask", "Agent"],
         },
         {
           name: "workflow-automation",
           desc: "Automate business processes with rule engine and task orchestration",
           sampleRequest: "Create business process automation workflow",
           icon: "$(play-circle)",
           modes: ["Ask", "Agent"],
         },
         {
           name: "mobile-development",
           desc: "Generate cross-platform mobile apps with code generation",
           sampleRequest: "Generate cross-platform mobile application code",
           icon: "$(device-mobile)",
           modes: ["Ask", "Agent"],
         },
         {
           name: "observability-intelligence",
           desc: "Collect metrics, logs, traces with dashboard and alerting",
           sampleRequest: "Setup observability with metrics and trace collection",
           icon: "$(eye)",
           modes: ["Ask", "Agent"],
         },
         {
           name: "search-indexing",
           desc: "Build full-text search with AI-powered ranking and relevance",
           sampleRequest: "Create full-text search index with AI ranking",
           icon: "$(search)",
           modes: ["Ask", "Agent"],
         },
         {
           name: "privacy-compliance",
           desc: "Implement privacy controls with compliance framework enforcement",
           sampleRequest: "Implement privacy compliance and data protection",
           icon: "$(shield)",
           modes: ["Ask", "Agent"],
         },
         {
           name: "identity-management",
           desc: "Manage identities with SSO, MFA, and access control",
           sampleRequest: "Configure identity management with SSO and MFA",
           icon: "$(person)",
           modes: ["Ask", "Agent"],
         },
         {
           name: "content-management",
           desc: "Manage documents with versioning, workflows, and retention",
           sampleRequest: "Create content management system with versioning",
           icon: "$(files)",
           modes: ["Ask", "Agent"],
         },
         {
           name: "advanced-analytics",
           desc: "Enable self-service analytics with BI tools and visualization",
           sampleRequest: "Build self-service BI dashboard with analytics",
           icon: "$(graph)",
           modes: ["Ask", "Agent"],
         },
         {
           name: "integration-iPaaS",
           desc: "Connect enterprise systems via integration platform",
           sampleRequest: "Create API integration between enterprise systems",
           icon: "$(link)",
           modes: ["Ask", "Agent"],
         },
         {
           name: "blockchain-integration",
           desc: "Integrate blockchain and Web3 capabilities into applications",
           sampleRequest: "Integrate smart contracts and blockchain APIs",
           icon: "$(circuit-board)",
           modes: ["Ask", "Agent"],
         },
         {
           name: "quality-assurance",
           desc: "Automate testing with coverage analysis and test reporting",
           sampleRequest: "Create test automation suite with coverage analysis",
           icon: "$(testing-run-icon)",
           modes: ["Ask", "Agent"],
         },
         // ═══════════════════════════════════════════════════════════════════
         // PHASE 6: ADVANCED INDUSTRIES & EMERGING TECHNOLOGIES (Modules 87-113)
         // ═══════════════════════════════════════════════════════════════════
         {
           name: "banking-fintech",
           desc: "Build banking solutions with PSD2, open banking, and regulations",
           sampleRequest: "Design open banking API architecture with compliance",
           icon: "$(credit-card)",
           modes: ["Ask", "Agent"],
         },
         {
           name: "healthcare-solutions",
           desc: "Create healthcare systems with HIPAA compliance and interoperability",
           sampleRequest: "Design HIPAA-compliant healthcare data system",
           icon: "$(heart)",
           modes: ["Ask", "Agent"],
         },
         {
           name: "retail-commerce",
           desc: "Build omnichannel retail with inventory and personalization",
           sampleRequest: "Design omnichannel retail platform with inventory",
           icon: "$(package)",
           modes: ["Ask", "Agent"],
         },
         {
           name: "manufacturing-iot",
           desc: "Enable manufacturing with IoT sensors and predictive maintenance",
           sampleRequest: "Setup IoT-enabled manufacturing with predictive maintenance",
           icon: "$(settings-gear)",
           modes: ["Ask", "Agent"],
         },
         {
           name: "logistics-tracking",
           desc: "Track logistics with real-time GPS and route optimization",
           sampleRequest: "Build logistics tracking with route optimization",
           icon: "$(map)",
           modes: ["Ask", "Agent"],
         },
         {
           name: "ml-models",
           desc: "Manage ML model registry with versioning and deployment",
           sampleRequest: "Create model registry and deploy machine learning models",
           icon: "$(beaker)",
           modes: ["Ask", "Agent"],
         },
         {
           name: "feature-engineering",
           desc: "Extract and transform features for ML pipelines",
           sampleRequest: "Design feature engineering pipeline for machine learning",
           icon: "$(wand)",
           modes: ["Ask", "Agent"],
         },
         {
           name: "model-serving",
           desc: "Deploy models with A/B testing and canary releases",
           sampleRequest: "Deploy ML model with A/B testing and monitoring",
           icon: "$(rocket)",
           modes: ["Ask", "Agent"],
         },
         {
           name: "synthetic-data",
           desc: "Generate synthetic data for testing and training",
           sampleRequest: "Generate synthetic training data for model validation",
           icon: "$(layers)",
           modes: ["Ask", "Agent"],
         },
         {
           name: "federated-learning",
           desc: "Enable privacy-preserving ML across distributed systems",
           sampleRequest: "Setup federated learning across distributed systems",
           icon: "$(group)",
           modes: ["Ask", "Agent"],
         },
         {
           name: "zero-trust-security",
           desc: "Implement zero-trust architecture with continuous verification",
           sampleRequest: "Design zero-trust security architecture",
           icon: "$(lock)",
           modes: ["Ask", "Agent"],
         },
         {
           name: "threat-detection",
           desc: "Detect threats with behavioral analysis and anomaly detection",
           sampleRequest: "Setup advanced threat detection with behavioral analysis",
           icon: "$(alert)",
           modes: ["Ask", "Agent"],
         },
         {
           name: "secrets-management",
           desc: "Manage secrets with rotation, audit, and policy enforcement",
           sampleRequest: "Configure secrets management with rotation policies",
           icon: "$(key)",
           modes: ["Ask", "Agent"],
         },
         {
           name: "supply-chain-security",
           desc: "Secure supply chain with provenance and verification",
           sampleRequest: "Implement supply chain security and provenance tracking",
           icon: "$(verified-filled)",
           modes: ["Ask", "Agent"],
         },
         {
           name: "soar-platform",
           desc: "Orchestrate security operations with automation and playbooks",
           sampleRequest: "Create security automation playbooks and orchestration",
           icon: "$(organization)",
           modes: ["Ask", "Agent"],
         },
         {
           name: "graph-database",
           desc: "Analyze relationships with graph queries and visualization",
           sampleRequest: "Design graph database schema and analyze relationships",
           icon: "$(bracket-dot)",
           modes: ["Ask", "Agent"],
         },
         {
           name: "timeseries-data",
           desc: "Manage time-series data with aggregation and retention",
           sampleRequest: "Design time-series database with retention policies",
           icon: "$(trending-up)",
           modes: ["Ask", "Agent"],
         },
         {
           name: "document-processing",
           desc: "Process documents with OCR and intelligent extraction",
           sampleRequest: "Setup document OCR and intelligent field extraction",
           icon: "$(file-text)",
           modes: ["Ask", "Agent"],
         },
         {
           name: "video-audio",
           desc: "Process video and audio with transcription and analysis",
           sampleRequest: "Create video processing pipeline with transcription",
           icon: "$(play)",
           modes: ["Ask", "Agent"],
         },
         {
           name: "spatial-mapping",
           desc: "Build geospatial applications with mapping and location services",
           sampleRequest: "Design geospatial mapping application with location services",
           icon: "$(target)",
           modes: ["Ask", "Agent"],
         },
         {
           name: "edge-computing",
           desc: "Deploy IoT edge computing with distributed processing",
           sampleRequest: "Design edge computing architecture for IoT devices",
           icon: "$(bracket)",
           modes: ["Ask", "Agent"],
         },
         {
           name: "5g-optimization",
           desc: "Optimize for 5G networks with low latency and throughput",
           sampleRequest: "Optimize application for 5G networks and latency",
           icon: "$(broadcast)",
           modes: ["Ask", "Agent"],
         },
         {
           name: "quantum-architecture",
           desc: "Integrate quantum computing with hybrid quantum-classical apps",
           sampleRequest: "Design hybrid quantum-classical computing architecture",
           icon: "$(pulse)",
           modes: ["Ask", "Agent"],
         },
         {
           name: "satellite-connectivity",
           desc: "Enable satellite connectivity for global coverage",
           sampleRequest: "Design satellite-enabled application architecture",
           icon: "$(broadcast)",
           modes: ["Ask", "Agent"],
         },
         {
           name: "mesh-networking",
           desc: "Build mesh networks with self-healing and resilience",
           sampleRequest: "Design self-healing mesh network architecture",
           icon: "$(network)",
           modes: ["Ask", "Agent"],
         },
         {
           name: "platform-governance",
           desc: "Govern platforms with policies, risk, and compliance",
           sampleRequest: "Create platform governance policies and frameworks",
           icon: "$(law)",
           modes: ["Ask", "Agent"],
         },
         {
           name: "enterprise-metrics",
           desc: "Build enterprise metrics catalog with lineage and governance",
           sampleRequest: "Create enterprise metrics catalog with data lineage",
           icon: "$(notebook)",
           modes: ["Ask", "Agent"],
         },
];


// ─── @participants (from package.nls.json) ────────────────────────────────────
export const PARTICIPANTS = [
  {
    name: "workspace",
    label: "@workspace",
    desc: "Ask questions about your codebase",
    sampleRequest: "How is authentication implemented in this project?",
    icon: "💼",
    commands: [
      { name: "explain",       desc: "Explain how the code in your active editor works" },
      { name: "fix",           desc: "Propose a fix for the problems in the selected code" },
      { name: "tests",         desc: "Generate unit tests for the selected code" },
      { name: "doc",           desc: "Add documentation comment for this symbol" },
      { name: "review",        desc: "Review the selected code in your active editor" },
      { name: "new",           desc: "Scaffold code for a new file or project in a workspace" },
      { name: "newNotebook",   desc: "Create a new Jupyter Notebook" },
      { name: "semanticSearch", desc: "Find relevant code to your query" },
      { name: "setupTests",    desc: "Set up tests in your project (Experimental)" },
    ],
  },
  {
    name: "vscode",
    label: "@vscode",
    desc: "Ask questions about VS Code",
    sampleRequest: "What is the command to open the integrated terminal?",
    icon: "🔵",
    commands: [
      { name: "api",     desc: "Ask about VS Code extension development" },
      { name: "search",  desc: "Generate query parameters for workspace search" },
      { name: "setupTests", desc: "Set up tests in your project (Experimental)" },
    ],
  },
  {
    name: "terminal",
    label: "@terminal",
    desc: "Ask about commands",
    sampleRequest: "How do I view all files within a directory including sub-directories?",
    icon: ">_",
    commands: [
      { name: "explain", desc: "Explain something in the terminal" },
    ],
  },
  {
    name: "github",
    label: "@github",
    desc: "Ask about GitHub issues, PRs, and repos",
    sampleRequest: "",
    icon: "🐙",
    commands: [],
  },
];

// ─── #variables ───────────────────────────────────────────────────────────────
export const VARIABLES = [
  { name: "file",                  desc: "Include the contents of a file" },
  { name: "selection",             desc: "The current selection in the active editor" },
  { name: "codebase",              desc: "Search your codebase for relevant code" },
  { name: "editor",                desc: "Contents of the active editor" },
  { name: "terminalLastCommand",   desc: "The last run command in the terminal" },
  { name: "terminalSelection",     desc: "The active terminal's selection" },
  { name: "problems",              desc: "Errors and warnings in the current file" },
  { name: "changes",               desc: "The currently changed files" },
];

// ─── Tool names (from toolNames.ts + package.nls.json) ───────────────────────
export const TOOL_NAMES: Record<string, string> = {
  // Core read tools
  semantic_search:              "Codebase",
  search_workspace_symbols:     "Workspace Symbols",
  read_file:                    "Read File",
  list_dir:                     "List Dir",
  file_search:                  "Find Files",
  grep_search:                  "Find Text In Files",
  read_project_structure:       "Project Structure",
  // Core edit tools
  create_file:                  "Create File",
  replace_string_in_file:       "Replace String in File",
  multi_replace_string_in_file: "Multi-Replace String in Files",
  insert_edit_into_file:        "Edit File",
  apply_patch:                  "Apply Patch",
  create_directory:             "Create Directory",
  // Execution tools
  run_in_terminal:              "Run in Terminal",
  get_terminal_output:          "Get Task Output",
  terminal_last_command:        "Terminal Last Command",
  terminal_selection:           "Terminal Selection",
  create_and_run_task:          "Create and Run Task",
  manage_todo_list:             "Manage Todo List",
  // VS Code interaction
  get_errors:                   "Get Problems",
  get_changed_files:            "Git Changes",
  get_vscode_api:               "Get VS Code API References",
  install_extension:            "Install Extension",
  run_vscode_command:           "Run VS Code Command",
  get_search_view_results:      "Search View Results",
  // Web
  fetch_webpage:                "Fetch Web Page",
  open_integrated_browser:      "Open Integrated Browser",
  github_repo:                  "Search GitHub Repository",
  // AI/agent
  memory:                       "Memory",
  manage_todo:                  "Manage Todo List",
  runSubagent:                  "Run Subagent",
  switch_agent:                 "Switch Agent",
  // Jupyter
  create_new_jupyter_notebook:  "Create New Jupyter Notebook",
  edit_notebook_file:           "Edit Notebook",
  run_notebook_cell:            "Run Notebook Cell",
  copilot_getNotebookSummary:   "Get Notebook Cell Output",
  read_notebook_cell_output:    "Read Cell Output",
  // Testing
  test_failure:                 "Test Failure",
  test_search:                  "Find Test Files",
  runTests:                     "Run Tests",
  // New workspace
  create_new_workspace:         "Create New Workspace",
  get_project_setup_info:       "Get Project Setup Info",
  // Mainframe / TN3270 Agent actions
  mf_write:         "Type Text",
  mf_ispf_command:  "ISPF Command",
  mf_tso_command:   "TSO Command",
  mf_keystroke:     "Send Key",
  mf_navigate:      "Navigate",
  mf_save:          "Save File",
  mf_cancel:        "Cancel / Exit",
  mf_submit:        "Submit Job",
  mf_delete:        "Delete Line",
  mf_insert:        "Insert Line",
  mf_compile:       "Compile",
  mf_search:        "Search Text",
  mf_replace:       "Replace Text",
  mf_sdsf_command:  "SDSF Command",
  mf_explain:       "Explain Screen",
  mf_move:          "Move Cursor",
};

// ─── Settings ─────────────────────────────────────────────────────────────────
export const SETTINGS_DEFAULTS = {
  model: "claude-sonnet-4-5",
  mode: "Ask" as Mode,
  temperature: 1.0,
  memory: true,
  tools: true,
  contextFiles: true,
  customInstructions: "",
  // API routing
  useMessagesApi: true,    // Use Anthropic Messages API for Claude models
  useResponsesApi: true,   // Use Responses API for o-series/gpt-5 models
  // Anthropic extended thinking
  thinkingBudgetTokens: 10240,
  thinkingEffort: "medium" as "none" | "low" | "medium" | "high",
  // Responses API reasoning
  responsesReasoningEffort: "high" as "low" | "medium" | "high",
  responsesReasoningSummary: "auto" as "none" | "auto" | "concise" | "detailed",
  // BYOK (Bring Your Own Key)
  anthropicApiKey: "",
  openaiApiKey: "",
  byokEndpoint: "",
  // Agent
  agentTemperature: 1.0,
  switchAgentEnabled: true,
  summarizeAgentHistory: true,
  // Features
  followUpSuggestions: true,
  braveSearchApiKey: "",
  // Context window management
  maxContextWindow: 80000,  // Adaptive default (users can adjust per model)
};
