// Simple format generators - no external dependencies

export function generateMarkdown(title: string, content: string, sections?: { heading: string; content: string }[]): string {
  let md = `# ${title}\n\n`;
  md += `> Generated: ${new Date().toLocaleString()}\n\n`;
  md += `---\n\n`;
  md += content + "\n\n";
  
  if (sections) {
    for (const section of sections) {
      md += `## ${section.heading}\n\n`;
      md += section.content + "\n\n";
    }
  }
  
  return md;
}

export function generateCsv(headers: string[], rows: string[][]): string {
  const escapeCsv = (val: string) => {
    if (val.includes(",") || val.includes('"') || val.includes("\n")) {
      return `"${val.replace(/"/g, '""')}"`;
    }
    return val;
  };
  
  let csv = headers.map(escapeCsv).join(",") + "\n";
  for (const row of rows) {
    csv += row.map(escapeCsv).join(",") + "\n";
  }
  return csv;
}

export function generateJson(title: string, data: unknown): string {
  return JSON.stringify({
    title,
    generated: new Date().toISOString(),
    data,
  }, null, 2);
}

export function generateText(title: string, content: string): string {
  let txt = `${"=".repeat(60)}\n`;
  txt += `${title}\n`;
  txt += `${"=".repeat(60)}\n`;
  txt += `Generated: ${new Date().toLocaleString()}\n`;
  txt += `${"─".repeat(60)}\n\n`;
  txt += content;
  return txt;
}

export function generateCode(content: string, language: string): string {
  const ext = language.toLowerCase();
  const commentChar = ext === "jcl" ? "//*" : ext === "sql" ? "--" : "*";
  
  let code = `${commentChar} ${language.toUpperCase()} - Generated by AI Copilot\n`;
  code += `${commentChar} ${new Date().toLocaleString()}\n`;
  code += `${commentChar} ${"─".repeat(50)}\n\n`;
  code += content;
  return code;
}
